import blobconverter
import cv2


FPS = 15    # Default is 30; reduce to 15 FPS

# 16:9 aspect ratio resolutions for 6x2 grid layout
RGB_RESOLUTION = (1920, 1080)  # Full HD 16:9
# RGB_RESOLUTION = (1280, 720)   # HD 16:9
# RGB_RESOLUTION = (1440, 1080)

FACE_DETECT_MODEL = blobconverter.from_zoo('face-detection-retail-0004', shaves=6)
CONFIDENCE_THRESHOLD = 0.5

DEBUG_MODE = True

# Main text font settings
MAIN_TEXT_FONT_SCALE = 1.2
MAIN_TEXT_FONT_WEIGHT = 2
MAIN_TEXT_VERTICAL_OFFSET = 25

# Available font types (for cycling with 'a' key)
AVAILABLE_FONTS = [
    cv2.FONT_HERSHEY_SIMPLEX,
    cv2.FONT_HERSHEY_PLAIN,
    cv2.FONT_HERSHEY_DUPLEX,
    cv2.FONT_HERSHEY_COMPLEX,
    cv2.FONT_HERSHEY_TRIPLEX,
    cv2.FONT_HERSHEY_COMPLEX_SMALL,
    cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
    cv2.FONT_HERSHEY_SCRIPT_COMPLEX
]

# Font names for display (matches order of AVAILABLE_FONTS)
FONT_NAMES = [
    "HERSHEY_SIMPLEX",
    "HERSHEY_PLAIN", 
    "HERSHEY_DUPLEX",
    "HERSHEY_COMPLEX",
    "HERSHEY_TRIPLEX",
    "HERSHEY_COMPLEX_SMALL",
    "HERSHEY_SCRIPT_SIMPLEX",
    "HERSHEY_SCRIPT_COMPLEX"
]

MAIN_TEXT_FONT_TYPE = AVAILABLE_FONTS[0]  # Default to first font

# Available font types:
# cv2.FONT_HERSHEY_SIMPLEX
# cv2.FONT_HERSHEY_PLAIN
# cv2.FONT_HERSHEY_DUPLEX
# cv2.FONT_HERSHEY_COMPLEX
# cv2.FONT_HERSHEY_TRIPLEX
# cv2.FONT_HERSHEY_COMPLEX_SMALL
# cv2.FONT_HERSHEY_SCRIPT_SIMPLEX
# cv2.FONT_HERSHEY_SCRIPT_COMPLEX